name: healthyride
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3
    - jupyter
    - dask
    - numpy
    - pandas
    - bokeh
    - matplotlib
    - geopy
    - pyproj
    - numba
    - requests
    - beautifulsoup4
    - html5lib
    - lxml
    - scipy
    - pip:
        - googlemaps
